### PR TITLE
Add new specs for directive with template url

### PR DESCRIPTION
**Pull request by enanox**
Hi @cironunes, I just wanted to share with you a strategy to load external directive templates (loaded with `templateUrl`).
It uses the `ngHtml2JS` preprocessor to load the external files on `$templateCache`, then allowing test specs to compile and inspect them as if they were inline templates.
I have no experience with `gulp`, so I'm not sure whether the contributions must add something to the `gulpfile.js`.

If you find this useful, let me know! 
See ya!

### CODE REVIEW

**Comment by cironunes** [comment]
Hi @enanox. 

Thanks for this. For sure it'll be useful.
There are just a few adjustment that I'm going to do later today and this can be merge.

BTW, Nice to meet you at JSConf UY!
See ya!

**Comment by enanox** [comment]
No problem :+1:, if there is something you'll need for me to do before merging, just let me know.
Cheers!

**Comment by cironunes** [comment]
Landed as 2f2c6b4200368ff5e78aed7d6c2817fca4ff150c.

Thanks @enanox!

**Comment by enanox** [comment]
Awesome! Thank you!

**Pull request closed without merging**
